[package]
name = "space-compiler"
version = "0.1.0"
authors = ["Covrick <asdfsdev264@gmail.com>"]
edition = "2018"

[dependencies]
compiler_module = { git = "https://github.com/Keshyu/compiler-module" }
phf = { version = "0.7.24", features = ["macros"] }
phf_codegen = "0.7.24"
